### ISSUE TITLE
[Errno 111] - Connection refused

### ISSUE THREAD

**Issue by NathanielJS1541** [weskerfoot/Spotify-MPD-Sync#2]
Hi,

I just cloned and installed Spotify-MPD-Sync and created the .env file as instructed in the readme. Whenever I try and run spotsync with the .env file sourced I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/spotsync", line 11, in <module>
    sys.exit(run_sync())
  File "/home/pi/.local/lib/python2.7/site-packages/spotify_mpd_sync/msplaylist/spotify.py", line 84, in run_sync
    spotify = Spotify()
  File "/home/pi/.local/lib/python2.7/site-packages/spotify_mpd_sync/msplaylist/spotify.py", line 20, in __init__
    self.mpd_client.connect("127.0.0.1", 6600)
  File "/home/pi/.local/lib/python2.7/site-packages/mpd/base.py", line 641, in connect
    self._sock = self._connect_tcp(host, port)
  File "/home/pi/.local/lib/python2.7/site-packages/mpd/base.py", line 604, in _connect_tcp
    raise err
socket.error: [Errno 111] Connection refused
```
Any ideas what I've done wrong?

**NOTE:** I have changed the title and content of this issue as it changed between reboots. I did not change the .env file so I have updated the issue.

**Comment by weskerfoot** [comment]
I'm going to add some documentation and make some changes to make it easier to manage the connection to MPD.

Most likely the issue is that you don't have MPD listening on `localhost:6600`

**Comment by weskerfoot** [comment]
You should be able to do `spotsync -H your_host_here -P your_port_here` now. See the README for an example. It will default to `localhost` and `6600` respectively. Hope that works for you!
